language: python
addons:
  firefox: "62.0.3"
sudo: true
cache:
  directories:
    - eggs
    - downloads
python: 2.7
install:
  - pip install -r requirements.txt
  - buildout -N buildout:download-cache=downloads annotate
  - buildout -t 30 buildout:download-cache=downloads
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install -q coveralls==0.5
  - coveralls
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
